Astra DB configuration doc update
JanusGraph/janusgraph pull request #2953
Opened 2022-01-18 20:14 UTC by kathirsvn

Fixing [#2945](https://github.com/JanusGraph/janusgraph/issues/2945)

Signed-off-by: Kathiresan Selvaraj <kathiresan.selvaraj@datastax.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

2022-01-18 22:39 UTC, porunov approved these changes
LGTM. Thank you @kathirsvn !

2022-01-18 22:55 UTC, mbrukman requested changes

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +For eg.
Please replace "For eg." with "For example:"

"e.g." already means "for example" – see https://en.wiktionary.org/wiki/e.g. – so "for eg." means "for for example".

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +Set the following property `storage.cql.internal.string-configuration` to `datastax-java-driver { basic.cloud.secure-connect-bundle=<path-to-secure-bundle-zip-file> }`
Remove "following" since it's specified right there.

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +and set the username, password and keyspace details
End sentence with a period.

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +Set the following property `storage.cql.internal.file-configuration` to an external configuration file if you would like to
Remove "following".

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +as per this [doc](https://docs.datastax.com/en/astra/docs/manage-application-tokens.html)_
End sentence with a period.

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +Note: To learn more about different configuration options of DataStax driver, please refer to the DataStax driver configuration
Please end sentence with a period.

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +_Client id and Client secret need to be generated and copied from your Astra Account
If this is something you'd like to highlight, maybe prepend it with "Note:" or "Important:" instead of using italics?

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +For eg.
Same as above.

2022-01-18 22:55 UTC, mbrukman commented on docs/storage-backend/cassandra.md
> +Note: To learn more about different configuration options of DataStax driver, please refer to the DataStax driver configuration
This doesn't need a "Note", it can just be "To learn more ..."

2022-01-26 18:40 UTC, kathirsvn commented
@mbrukman My EasyCLA has been cleared (and all the review comments have been incorporated as well). Can we merge this change please?

2022-01-28 15:27 UTC, porunov approved these changes

2022-01-28 15:29 UTC, porunov commented
@mbrukman I think requested changes have been fixed. I'm going to merge this PR tomorrow unless there are other comments

2022-01-28 17:53 UTC, mbrukman approved these changes
LGTM

2022-01-28 17:53 UTC, merged